<a href="https://colab.research.google.com/github/Sai0210/Home_Assignment_4/blob/main/Question3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import torch
import torch.nn.functional as F

def scaled_dot_product_attention(Q, K, V):

    # Convert numpy arrays to PyTorch tensors
    Q_torch = torch.tensor(Q, dtype=torch.float32)
    K_torch = torch.tensor(K, dtype=torch.float32)
    V_torch = torch.tensor(V, dtype=torch.float32)

    # 1. Compute the dot product of Q and K transpose
    matmul_qk = torch.matmul(Q_torch, K_torch.transpose(-2, -1))  # (..., seq_len_q, seq_len_k)

    # 2. Scale the result by dividing by sqrt(d_k)
    d_k = K.shape[-1]
    scaled_attention_logits = matmul_qk / np.sqrt(d_k)

    # 3. Apply softmax to get attention weights
    attention_weights = F.softmax(scaled_attention_logits, dim=-1)  # (..., seq_len_q, seq_len_k)

    # 4. Multiply the weights by V to get the output
    output = torch.matmul(attention_weights, V_torch)  # (..., seq_len_q, d_v)

    return attention_weights.numpy(), output.numpy()

if __name__ == "__main__":
    Q = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
    K = np.array([[1, 0, 1, 0], [0, 1, 0, 1]])
    V = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

    attention_weights, output = scaled_dot_product_attention(Q, K, V)

    print("Attention Weights (after softmax):")
    print(attention_weights)
    print("\nOutput Matrix:")
    print(output)

Attention Weights (after softmax):
[[0.7310586  0.26894143]
 [0.26894143 0.7310586 ]]

Output Matrix:
[[2.0757656 3.0757658 4.0757656 5.0757656]
 [3.9242344 4.9242344 5.9242344 6.9242344]]
